CREATE TABLE brands
(
    id   BINARY(16) PRIMARY KEY DEFAULT (UNHEX(REPLACE(UUID(), '-', ''))),
    name VARCHAR(100) NOT NULL UNIQUE
);

CREATE INDEX idx_brands_name ON brands (name);

INSERT INTO brands (name)
VALUES ('Acura'),
       ('Agrale'),
       ('Alfa Romeo'),
       ('AM General'),
       ('Asia Motors'),
       ('Aston Martin'),
       ('Audi'),
       ('Baby'),
       ('BMW'),
       ('BRM'),
       ('Bugre'),
       ('BYD'),
       ('CAB Motors'),
       ('Cadillac'),
       ('Chery'),
       ('CBT Jipe'),
       ('Chana'),
       ('Changan'),
       ('Chevrolet'),
       ('Chrysler'),
       ('Citroën'),
       ('Cross Lander'),
       ('D2D Motors'),
       ('Daewoo'),
       ('Daihatsu'),
       ('DFSK'),
       ('Dodge'),
       ('EFFA'),
       ('Engesa'),
       ('Envemo'),
       ('Ferrari'),
       ('FEVER'),
       ('Fiat'),
       ('Fibravan'),
       ('Ford'),
       ('Foton'),
       ('Fyber'),
       ('GAC'),
       ('Geely'),
       ('Great Wall'),
       ('Gurgel'),
       ('GWM'),
       ('Hafei'),
       ('Hitech Electric'),
       ('Honda'),
       ('Hyundai'),
       ('Isuzu'),
       ('Iveco'),
       ('JAC'),
       ('Jaecoo'),
       ('Jaguar'),
       ('Jeep'),
       ('Jinbei'),
       ('JPX'),
       ('Kia'),
       ('Lada'),
       ('Lamborghini'),
       ('Land Rover'),
       ('Lexus'),
       ('Lifan'),
       ('Lobini'),
       ('Lotus'),
       ('Mahindra'),
       ('Maserati'),
       ('Matra'),
       ('Mazda'),
       ('McLaren'),
       ('Mercedes-Benz'),
       ('Mercury'),
       ('MG'),
       ('Mini'),
       ('Mitsubishi'),
       ('Miura'),
       ('Neta'),
       ('Nissan'),
       ('Omoda'),
       ('Peugeot'),
       ('Plymouth'),
       ('Pontiac'),
       ('Porsche'),
       ('RAM'),
       ('Rely'),
       ('Renault'),
       ('Rolls-Royce'),
       ('Rover'),
       ('Saab'),
       ('Saturn'),
       ('Seat'),
       ('Seres'),
       ('Shineray'),
       ('Smart'),
       ('SsangYong'),
       ('Subaru'),
       ('Suzuki'),
       ('TAC'),
       ('Toyota'),
       ('Troller'),
       ('Volkswagen'),
       ('Volvo'),
       ('Wake'),
       ('Walk'),
       ('Zeekr');